development:
  gamertiser: gamertiser_dev
  access_key_id: AKIAIYNGOFHLH5736P2Q
  secret_access_key: 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
test:
  gamertiser: gamertiser_test
  access_key_id: AKIAIYNGOFHLH5736P2Q
  secret_access_key: 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
production:
  gamertiser: gamertiser_pro
  access_key_id: AKIAIYNGOFHLH5736P2Q
  secret_access_key: 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
